# Generated by Django 5.2.17 on 2026-09-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('usersub', models.ForeignKey(db_column='usersub_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refund', 'Refund')], default='pending', max_length=20)),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice')),
                ('usersub', models.ForeignKey(db_column='usersub_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
