# Generated by Django 6.0.7 on 2026-09-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_patient'),
        ('patient_dashboard', '0003_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_dashboard.patient'),
        ),
    ]
