# Generated by Django 5.2.16 on 2026-08-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualifications', models.FileField(upload_to='')),
                ('experience', models.TextField(max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(null=True)),
                ('nic_number', models.CharField(max_length=20, unique=True)),
                ('professional_code', models.CharField(max_length=10, unique=True)),
                ('verify_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot', models.IntegerField()),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalsLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
        ),
    ]
