# Generated by Django 5.2.16 on 2026-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='qualifications_file',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='qualifications',
            field=models.TextField(),
        ),
    ]
