# Generated by Django 5.2.16 on 2026-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_professionals_qualifications_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='service_type',
            field=models.CharField(choices=[('doctor', 'Doctor Home Visit'), ('nursing', 'Nursing Care'), ('lab', 'Laboratory Testing')], default='doctor', max_length=20),
            preserve_default=False,
        ),
    ]
