# Generated by Django 5.2.16 on 2026-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professionals_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionals',
            name='User',
        ),
        migrations.AlterField(
            model_name='professionals',
            name='service_type',
            field=models.CharField(choices=[('doctor', 'Doctor Home Visit'), ('nursing', 'Nursing Care'), ('mlt', 'Medical Laboratory Technologist (MLT)'), ('physiotherapist', 'Physiotherapist'), ('caregiver', 'Caregiver'), ('nutritionist', 'Nutritionist'), ('counselor', 'Mental Health Counselor')], max_length=20),
        ),
    ]
