# Generated by Django 6.0.7 on 2026-08-29 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_wallet', '0001_initial'),
        ('patient_dashboard', '0003_patient_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='professionalpatientaccess',
            constraint=models.UniqueConstraint(fields=('patient', 'professional'), name='unique_patient_professional_access'),
        ),
    ]
