# Generated by Django 6.0.7 on 2026-08-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Anuradhapura', 'Anuradhapura'), ('Badulla', 'Badulla'), ('Batticaloa', 'Batticaloa'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota'), ('Jaffna', 'Jaffna'), ('Kalutara', 'Kalutara'), ('Kandy', 'Kandy'), ('Kegalle', 'Kegalle'), ('Kilinochchi', 'Kilinochchi'), ('Kurunegala', 'Kurunegala'), ('Mannar', 'Mannar'), ('Matale', 'Matale'), ('Matara', 'Matara'), ('Monaragala', 'Monaragala'), ('Mullaitivu', 'Mullaitivu'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Puttalam', 'Puttalam'), ('Ratnapura', 'Ratnapura'), ('Trincomalee', 'Trincomalee'), ('Vavuniya', 'Vavuniya')], max_length=20),
        ),
    ]
