# Generated by Django 5.2.17 on 2026-09-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(choices=[('free plan', 'Free Plan'), ('family plan', 'Family Plan'), ('senior care plan', 'Senior Care Plan'), ('overseas parent care plan', 'Overseas Parent Care Plan')], default='free plan', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('max_profile', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('usersub_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('pending', 'Pending')], default='activated', max_length=20)),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('sub_historyid', models.AutoField(primary_key=True, serialize=False)),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='subscriptions.subscriptionplan')),
                ('usersub', models.ForeignKey(db_column='usersub_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscription_history',
            },
        ),
    ]
