# Generated by Django 6.0.7 on 2026-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0002_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profiles/'),
        ),
    ]
